
USER_AUTHENTICATION_QUERY = "SELECT USER_NAME FROM USER_AUTH WHERE USER_ID=? AND PASSWORD=?"

ALL_LOCATIONS_QUERY = "SELECT MAP_ROW, MAP_COLUMN, STORE_NAME " \
                       "FROM  STORES, LOCATIONS " \
                       "WHERE LOCATIONS.STORE_ID = STORES.STORE_ID"


# [(0, 0, KFC), (1,0, BK),....]
