# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginqt/form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from controllers.login_controller import LoginController


class Ui_qtlogin(object):

    def __init__(self):
        self._login_controller = LoginController()

    def setupUi(self, qtlogin):
        qtlogin.setObjectName("qtlogin")
        qtlogin.resize(372, 430)
        self.centralwidget = QtWidgets.QWidget(qtlogin)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 130, 61, 21))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(170, 130, 104, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 160, 61, 21))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(170, 160, 104, 21))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 220, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        # self.label_3.setGeometry(QtCore.QRect(160, 290, 60, 16))
        self.label_3.setGeometry(QtCore.QRect(20, 290, 331, 20))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        qtlogin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(qtlogin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 372, 24))
        self.menubar.setObjectName("menubar")
        self.menuLogin = QtWidgets.QMenu(self.menubar)
        self.menuLogin.setObjectName("menuLogin")
        qtlogin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(qtlogin)
        self.statusbar.setObjectName("statusbar")
        qtlogin.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuLogin.menuAction())

        self.retranslateUi(qtlogin)
        QtCore.QMetaObject.connectSlotsByName(qtlogin)

        self.init_signals()

    def retranslateUi(self, qtlogin):
        _translate = QtCore.QCoreApplication.translate
        qtlogin.setWindowTitle(_translate("qtlogin", "Welcome"))
        self.label.setText(_translate("qtlogin", "User ID:"))
        self.label_2.setText(_translate("qtlogin", "Password"))
        self.pushButton.setText(_translate("qtlogin", "Login"))
        self.menuLogin.setTitle(_translate("qtlogin", "Login"))

    def init_signals(self):
        self.pushButton.clicked.connect(
            lambda: self.onClick()

        )

    def onClick(self):
        x = self._login_controller.on_login_request(self.textEdit.toPlainText(),
                                                self.textEdit_2.toPlainText())
        print(x)
        self.label_3.setText(x)


